### ISSUE TITLE
Ability to disable logging

### ISSUE THREAD

**Issue by piotrpalarz** [mxl/laravel-queue-rate-limit#5]
Could you please add an ability to disable logging? I'm using Larave 5.* version.

**Comment by mxl** [comment]
Fixed in https://github.com/mxl/laravel-queue-rate-limit/commit/6f19d4a0546f8e5309de82be4753d5a44b5fc784.

See https://github.com/mxl/laravel-queue-rate-limit#disable-logging.

**Comment by piotrpalarz** [comment]
Thank you! I was about to figure it out myself. Logs were getting close to 80MB per day. Now it's working as expected. FYI I use this package to limit Amazon SES queue to imposed rate of 14 emails per second. It's been very useful and now without logging it's perfect!
