### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by xxdalexx** [mxl/laravel-queue-rate-limit#6]
Dependency issues:

    - mxl/laravel-queue-rate-limit v2.0.1 requires illuminate/queue ^6.0 -> satisfiable by laravel/framework[v6.18.0, 6.x-dev], illuminate/queue[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - mxl/laravel-queue-rate-limit v2.0.0 requires illuminate/log ^6.0 -> satisfiable by laravel/framework[v6.18.0, 6.x-dev], illuminate/log[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - mxl/laravel-queue-rate-limit v2.0.1 requires illuminate/log ^6.0 -> satisfiable by laravel/framework[v6.18.0, 6.x-dev], illuminate/log[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].

**Comment by mxl** [comment]
Fixed in #7 by @thijsdejong 👍
